/**
 * Generated by orval. Do not edit manually.
 * e6ai API
 * e621ng 2da4b89799b7799a4920adfe14112939976b4fcd
 */

export interface Tags {
  /** An array of general tags */
  general: string[];
  /** An array of artist tags */
  director: string[];
  /** An array of contributor tags */
  contributor: string[];
  /** An array of copyright tags */
  franchise: string[];
  /** An array of character tags */
  character: string[];
  /** An array of species tags */
  species: string[];
  /** An array of invalid tags */
  invalid: string[];
  /** An array of meta tags */
  meta: string[];
  /** An array of lore tags */
  lore: string[];
}
